feat: secret file structure updates
Closes #1

diff --git a/files/run-cloudflared b/files/run-cloudflared
--- a/files/run-cloudflared
+++ b/files/run-cloudflared
@@ -63,6 +63,7 @@ function print_usage() {
   echo "Options:"
   echo
   wrap "$(
+    echo -e "--role|The instance role, one of \"server\", \"client\" or \"bastion\"."
     echo -e "--region|Cloudflare region."
     echo -e "--secrets-bucket-name|AWS S3 secrets bucket name."
   )"
@@ -148,11 +149,17 @@ function run() {
 
   local secrets_bucket_name=""
   local region="us"
+  local role=""
 
   while [[ $# -gt 0 ]]; do
     local key="$1"
 
     case "$key" in
+      --role)
+        assert_not_empty "$key" "$2"
+        role="$2"
+        shift
+        ;;
       --secrets-bucket-name)
         assert_not_empty "$key" "$2"
         secrets_bucket_name="$2"
@@ -178,19 +185,45 @@ function run() {
   done
 
   assert_not_empty "--secrets-bucket-name" "$secrets_bucket_name"
+  assert_not_empty "--role" "$role"
+
+  if ! [[ "$role" == "server" || "$role" == "client" || "$role" == "bastion" ]]; then
+    log_error "Unrecognized value for the --role flag."
+    exit 1
+  fi
 
   local -r config_file="/opt/cloudflared/config/default"
 
   local tunnel_token
 
-  tunnel_token="$(get_object_value "${secrets_bucket_name}" "bastion/cloudflared/cloudflared-tunnel-token")"
+  tunnel_token="$(get_object_value "${secrets_bucket_name}" "${role}/cloudflared/cloudflared-tunnel-token")"
 
   get_object "${secrets_bucket_name}" \
-    "bastion/nomad/nomad-ca.pem" \
+    "${role}/nomad/nomad-ca.pem" \
     "/etc/pki/ca-trust/source/anchors/nomad-ca.pem" "root" || log_warn "Unable to download \"nomad/nomad-ca.pem\""
 
   if [[ -f "/etc/pki/ca-trust/source/anchors/nomad-ca.pem" ]]; then
     chmod 644 "/etc/pki/ca-trust/source/anchors/nomad-ca.pem"
+
+    update-ca-trust
+  fi
+
+  get_object "${secrets_bucket_name}" \
+    "${role}/consul-terraform-sync/consul-terraform-sync-ca.pem" \
+    "/etc/pki/ca-trust/source/anchors/consul-terraform-sync-ca.pem" "root" || log_warn "Unable to download \"consul-terraform-sync/consul-terraform-sync-ca.pem\""
+
+  if [[ -f "/etc/pki/ca-trust/source/anchors/consul-terraform-sync-ca.pem" ]]; then
+    chmod 644 "/etc/pki/ca-trust/source/anchors/consul-terraform-sync-ca.pem"
+
+    update-ca-trust
+  fi
+
+  get_object "${secrets_bucket_name}" \
+    "${role}/vault/vault-ca.pem" \
+    "/etc/pki/ca-trust/source/anchors/vault-ca.pem" "root" || log_warn "Unable to download \"vault/vault-ca.pem\""
+
+  if [[ -f "/etc/pki/ca-trust/source/anchors/vault-ca.pem" ]]; then
+    chmod 644 "/etc/pki/ca-trust/source/anchors/vault-ca.pem"
 
     update-ca-trust
   fi
